### ISSUE TITLE
App crashes if FirebseAuth is involved. 

### ISSUE THREAD

**Issue by allco** [xyxyLiu/TaskLogger#2]
App crashes with:    
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.drivekitt.mcar.debug:taskLogger, PID: 3039
    java.lang.RuntimeException: Unable to create application com.drivekitt.mcar.BaseApplication: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.drivekitt.mcar.debug:taskLogger. Make sure to call FirebaseApp.initializeApp(Context) first.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5887)
        at android.app.ActivityThread.access$1100(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6680)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.drivekitt.mcar.debug:taskLogger. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(com.google.firebase:firebase-common@@16.0.2:240)
        at com.firebase.ui.auth.AuthUI.getInstance(AuthUI.java:188)
        at com.drivekitt.mcar.ioc.FirebaseModule.providesAuthUI(FirebaseModule.kt:78)
        at com.drivekitt.mcar.ioc.FirebaseModule_ProvidesAuthUIFactory.proxyProvidesAuthUI(FirebaseModule_ProvidesAuthUIFactory.java:34)
        at com.drivekitt.mcar.ioc.FirebaseModule_ProvidesAuthUIFactory.provideInstance(FirebaseModule_ProvidesAuthUIFactory.java:25)
        at com.drivekitt.mcar.ioc.FirebaseModule_ProvidesAuthUIFactory.get(FirebaseModule_ProvidesAuthUIFactory.java:21)
        at com.drivekitt.mcar.ioc.FirebaseModule_ProvidesAuthUIFactory.get(FirebaseModule_ProvidesAuthUIFactory.java:8)
     
```

Possible workaround is remove process affinity for the service `android:process=":taskLogger"`.

**Comment by thisames** [comment]
put 'com.google.gms.google-services' on plugins in app/build.gradle and be happy

```
plugins {
    id 'com.google.gms.google-services'
}
```
